config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  resources :locations do
    resources :reviews, only: [:new, :create]
  end

  namespace :account do
    resource :profile, only: [:show, :edit, :update]
    resources :reviews, only: [:edit, :update, :destroy]
  end

  resources :messagecontacts, only: [:create]

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

end

app/views/shared/_flashes.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <% if notice %>
        <div class="alert alert-info alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= notice %>
        </div>
      <% end %>
      <% if alert %>
        <div class="alert alert-warning alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= alert %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div id="footer">
 <div class="container">
   <div class="row">
     <ul class="list-inline text-center">
       <li>
       <%= link_to "https://www.facebook.com/", :class=>'footer-button' do %>
         <i class="fa fa-facebook"></i>
       <% end %>
       </li>
       <li>
         <%= link_to "https://twitter.com/?lang=fr", :class=>'footer-button' do %>
           <i class="fa fa-twitter"></i>
         <% end %>
       </li>
       <li>
         <%= link_to "https://www.youtube.com/?hl=fr&gl=FR", :class=>'footer-button'  do %>
           <i class="fa fa-youtube"></i>
         <% end %>
       </li>
       <li><%= link_to "Contact Us", page_path(:contact), class: "footer-text" %></li>
     </ul>
   </div>
 </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-wagon" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="home-icon">
        <%= link_to root_path do %>
        <i class="fa fa-home"></i> GOMOBILY
        <% end %>
      </div>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <% if @location && @location.id %>
          <li>
          <%= link_to t(".top_call_to_action", default: "Leave a review"), new_location_review_path(@location), class: "btn btn-review" %>
          </li>
          <% end %>
          <li>
            <%= link_to t(".top_call_to_action", default: "Add a location"), new_location_path, class: "btn" %>
          </li>
          <li class="dropdown">
            <%= link_to "#", {class: "dropdown-toggle", "data-toggle" => "dropdown", "role" => "button", "aria-expanded" => "false"} do %>
              Welcome <%= current_user.name %> <span class="caret"></span>
            <% end %>
            <ul class="dropdown-menu" role="menu">
              <li>
                <%= link_to account_profile_path do %>
                  <i class="fa fa-user"></i> <%= t(".profile", default: "My profile") %>
                <% end %>
              </li>
              <li>
                <%= link_to edit_user_registration_path  do %>
                  <i class="fa fa-pencil"></i> <%= t ".profile", default: "Edit my profile" %>
                <% end %>
            </ul>
          </li>
        <% else %>
          <li>
            <%= link_to new_user_session_path do %>
              <i class="fa fa-sign-in"></i>

              <%= t(".log_in", default: "Log in") %>

            <% end %>
          </li>
          <li>
            <%= link_to new_user_registration_path do %>
              <i class="fa fa-pencil"></i>
              <%= t(".sign_up", default: "Sign up") %>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>