config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  resources :locations do
    resources :reviews, only: [:new, :create]
  end

  namespace :account do
    resource :profile, only: [:show, :edit, :update]
    resources :reviews, only: [:edit, :update, :destroy]
  end

  resources :messagecontacts, only: [:create]

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

end

app/controllers/account/reviews_controller.rb
module Account
  class ReviewsController < ApplicationController
    before_action :authenticate_user!

    def edit
      @review = Review.find(params[:id])
      authorize @review
    end

    def update
      @review = Review.find(params[:id])
      authorize @review
      @review.update(review_params)
      redirect_to account_profile_path
    end

    def destroy
      @review = Review.find(params[:id])
      authorize @review
      @review.destroy
      redirect_to account_profile_path
    end

    def review_params
      params.require(:review).permit(:content, :rating)
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_location

  def new
    @review = Review.new
    @review.location = @location
    authorize @review
  end

  def create
    @review = @location.reviews.build(review_params)
    @review.user = current_user
    authorize @review
    if @review.save
      redirect_to location_path(@location)
    else
      render :new
    end
  end

  private

  def set_location
    @location = Location.find(params[:location_id])
  end

  def review_params
    params.require(:review).permit(:rating, :content, :user_id)
  end
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/views/reviews/new.html.erb
<div class="card" id="review-form-container">
  <div class="container">
    <div class="row">
      <div class="col-xs-offset-2 col-xs-8">
          <h1>Write a review for <%= @location.name.capitalize %></h1>
          <% form_id = "#{@location.id}_rating" %>
          <%= simple_form_for [@location, @review], :html => {:id => "#{form_id}"} do |f| %>
            <%#= f.hidden_field :location_id %>
            <%= f.hidden_field :rating, :id => "#{form_id}_stars", value: 0 %>
            <% (1..5).each do |i| %>
              <i class="fa fa-star star_rating" data-stars="<%= i %>" data-form-id="<%= "#{form_id}_#{i}" %>" id="<%= "#{form_id}_#{i}" %>"></i>
            <% end %>
            <span>(Score out of 5)</span>
            <div class="padded-small"></div>


            <%= f.input :content, :cols => "40", :rows => "10", input_html: { placeholder: "Your review helps others know accessibility about awesome locations", class: "form-control" }%>

            <%= f.submit "Post my review"%>
            <%= link_to 'Cancel', location_reviews_path %>
          <% end %>

          <div class="row">
            <div class="col-xs-12">
              <p class="text-center location-back">
                <%= link_to :back do  %>
                  <i class="fa fa-arrow-left"></i> Back
                <% end %>
              </p>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>