config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  resources :locations do
    resources :reviews, only: [:new, :create]
  end

  namespace :account do
    resource :profile, only: [:show, :edit, :update]
    resources :reviews, only: [:edit, :update, :destroy]
  end

  resources :messagecontacts, only: [:create]

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

end

app/models/location.rb
# == Schema Information
#
# Table name: locations
#
#  id                 :integer          not null, primary key
#  name               :string
#  description        :text
#  telephone          :string
#  website            :string
#  email              :string
#  photo_file_name    :string
#  photo_content_type :string
#  photo_file_size    :integer
#  photo_updated_at   :datetime
#  street             :string
#  city               :string
#  postcode           :string
#  location_category  :string
#  validated          :boolean
#  wheelchair_access  :boolean
#  step_free_access   :boolean
#  automatic_doors    :boolean
#  disabled_parking   :boolean
#  accessible_toilets :boolean
#  user_id            :integer
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  latitude           :float
#  longitude          :float
#
# Indexes
#
#  index_locations_on_user_id  (user_id)
#

class Location < ActiveRecord::Base
  belongs_to :user
  has_many :reviews, dependent: :destroy
  has_and_belongs_to_many :categories
  # has_and_belongs_to_many :locations_options

  has_attached_file :photo,
    styles: { medium: "300x300>", thumb: "x100" }

  validates_attachment_content_type :photo,
    content_type: /\Aimage\/.*\z/

  scope :validated, -> { where(validated: true) }

  before_save :check_website, if: :website_changed?

  geocoded_by :full_address
  after_validation :geocode, if: ->(location){
    location.street.present? && location.street_changed?
    location.city.present? && location.city_changed?
    location.postcode.present? && location.postcode_changed?
    }

  def check_website
    unless self.website[/\Ahttp:\/\//] || self.website[/\Ahttps:\/\//]
      self.website = "http://#{self.website}"
    end
  end

  def full_address
     "#{street} #{city} #{postcode}"
  end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @locations = policy_scope(Location)

    @categorytype = params[:categorytype]
    @category = params[:category]

    if params[:category].present?
      @locations = Location.paginate(:page => params[:page], :per_page => 10).where(location_category: params[:category])


    elsif params[:name].present?
      @locations = Location.paginate(:page => params[:page], :per_page => 10).where(name: params[:name])
    else
      @locations = Location.all.paginate(:page => params[:page], :per_page => 10)
    end


    @locations = @locations.where(wheelchair_access: true) if params.has_key? :wheelchair_access
    @locations = @locations.where(step_free_access: true) if params.has_key? :step_free_access
    @locations = @locations.where(automatic_doors: true) if params.has_key? :automatic_doors
    @locations = @locations.where(disabled_parking: true) if params.has_key? :disabled_parking
    @locations = @locations.where(accessible_toilet: true) if params.has_key? :accessible_toilet



    @markers = Gmaps4rails.build_markers(@locations) do |location, marker|
      marker.lat location.latitude
      marker.lng location.longitude
      marker.infowindow view_context.link_to(location.name, location_path(location))
    end


    @markers.reject! do |marker|
      marker[:lat].blank? || marker[:lng].blank?
    end
    authorize @locations

  end

  # marker.picture { :picture => <marker-picture-file-path> })
  # marker.json({ :id => user.id })

  # def select
  #   @location = Location.find(params[:id])
  #   authorize @location
  #   @location.destroy
  #   redirect_to root_path
  # end

  def show
    @location = Location.find(params[:id])
    authorize @location


    @markers = Gmaps4rails.build_markers(@location) do |location, marker|
    marker.lat location.latitude
    marker.lng location.longitude
    end

  end

  def new
    @location = Location.new
    authorize @location
  end

  # create needs admin approval
  def create
    @location = current_user.locations.new(location_params)
    authorize @location

    if @location.save
      redirect_to location_path(@location)
    else
      render :new
    end
  end

  def edit
    @location = Location.find(params[:id])
    authorize @location
  end

  # update and destroy needs to be admin only
  def update
    @location = Location.find(params[:id])
    authorize @location
    @location.update(location_params)
    redirect_to location_path
  end

  def destroy
    @location = Location.find(params[:id])
    authorize @location
    @location.destroy
    redirect_to root_path
  end


  private

  def location_params
    params.require(:location).permit(:name, :description, :website, :email, :telephone, :street, :city, :postcode,
    :location_category, :validated, :wheelchair_access, :step_free_access, :automatic_doors, :disabled_parking,
    :accessible_toilets, :latitude, :longitude, :photo, :picture)
  end

end

app/helpers/location_helper.rb
module LocationHelper
end

app/views/locations/edit.html.erb
<div class="container">
  <div class="card">
    <h1 class="text-center">Edit Location</h1>
      <div class="row">
        <div class="col-md-6 col-md-offset-3 col-xs-12">
            <div class="form">
               <%= simple_form_for @location, html: {multipart: true} do |f| %>
              <%= f.input :name %>
              <%= f.input :description %>
              <%= f.input :telephone %>
              <%= f.input :website %>
              <%= f.input :email %>
              <%= f.label :photo %>
              <%= f.file_field :photo %>
              <%= f.input :street %>
              <%= f.input :city %>
              <%= f.input :postcode %>
              <%= f.input :location_category, collection: [
                'Accommodation',
                'Bar/cafe',
                'Cinema',
                'Cultural site',
                'Museum/Gallery',
                'Park',
                'Public transport',
                'Restaurant'] %>
              <!-- %= f.input :validated, wrapper: :vertical_boolean %> -->
              <%= f.input :wheelchair_access, wrapper: :vertical_boolean %>
              <%= f.input :step_free_access, wrapper: :vertical_boolean %>
              <%= f.input :automatic_doors, wrapper: :vertical_boolean %>
              <%= f.input :disabled_parking, wrapper: :vertical_boolean %>
              <%= f.input :accessible_toilets, wrapper: :vertical_boolean %>
              <%= f.button :submit, "Update listing", :class => "btn" %>
            <% end %>
            <div class="home-icon"></div>
            <i class="fa fa-trash-o"></i><%= link_to 'Cancel', locations_path %>

          <div class="row">
            <div class="col-xs-12">
              <p class="text-center location-back">
                <%= link_to :back do  %>
                  <i class="fa fa-arrow-left"></i> Back
                <% end %>
              </p>
            </div>
          </div>

          </div>
        </div>
      </div>
  </div>

app/views/locations/index.html.erb
<div class="card">
  <h1 class="text-center">What do you want to do?</h1>
  <div class="container">
    <div class="row">
      <div class="col-xs-7 listing">
        <%= form_tag locations_path, :method => :get do %>
          <div class="form-inline text-center">
            <%= select_tag :categorytype, options_for_select(['Eat', 'Fun', 'Move', 'Stay'], @categorytype), prompt: "What?", class: "form-control" %>


            <%= select_tag :category, options_for_select(select_options_category(params[:categorytype]), @category), prompt: "Choose a category", class: "form-control" %>
            <%= text_field_tag(:name, nil, placeholder: "Enter name eg London Eye", class: "form-control") %>

            <%= submit_tag "Search", :name => nil, class: "btn btn-primary btn-lg" %>
          </div>
        </div>
          <div class="checkboxes">
            <div class="col-xs-2">
              <h4>Accessibility</h4>
              <ul class="list-unstyled">
                <li>
                  <% if params[:wheelchair_access] %>
                  <%= check_box_tag(:wheelchair_access, "1", true) %>
                  <% else %>
                    <%= check_box_tag(:wheelchair_access, "1", false) %>
                  <% end %>
                  <%= label_tag :wheelchair_access %>
                </li>
                <li>
                  <% if params[:step_free_access] %>
                    <%= check_box_tag(:step_free_access, "1", true) %>
                  <% else %>
                    <%= check_box_tag(:step_free_access, "1", false) %>
                  <% end %>
                  <%= label_tag :step_free_access %>
                </li>
              </ul>
            </div>
          </div>
          <div class="checkboxes">
            <div class="col-xs-2">
              <h4>Services</h4>
              <ul class="list-unstyled">
                <li>
                  <% if params[:automatic_doors] %>
                    <%= check_box_tag(:automatic_doors, "1", true) %>
                  <% else %>
                    <%= check_box_tag(:automatic_doors, "1", false) %>
                  <% end %>
                  <%= label_tag :automatic_doors %>
                </li>
                <li>
                  <% if params[:disabled_parking] %>
                    <%= check_box_tag(:disabled_parking, "1", true) %>
                  <% else %>
                    <%= check_box_tag(:disabled_parking, "1", false) %>
                  <% end %>
                  <%= label_tag :disabled_parking %>
                </li>
                <li>
                  <% if params[:accessible_toilets] %>
                    <%= check_box_tag(:accessible_toilets, "1", true) %>
                  <% else %>
                    <%= check_box_tag(:accessible_toilets, "1", false) %>
                  <% end %>
                  <%= label_tag :accessible_toilets %>
                </li>
              </ul>
            </div>
          </div>
        <% end %>
        </div>
      </div>
    </div>
  </div>
  </div>
</div>



<!-- ########################### CARDS Listing-->
  <div class="card">
    <div class="row">
      <div class="col-xs-6">
      <%= will_paginate @locations, :class => 'digg_pagination padding-left' %>
        <div class="listing text-center">
          <div class="row">
          <% @locations.each do |location| %>
            <div class="col-xs-6">
              <p class="location-details"><%= location.name.titleize %></p>
              <% if location.photo? %>
              <%= image_tag location.photo.url(:thumb), height: '100px', width: '100px', :class=> "img-show" %>
              <% else %>
              <%= image_tag 'placeholder.jpg', height: '100px', :class=> "img-show" %>
              <% end %>
              <p><%= link_to "View location", location_path(location), class: "btn btn-primary btn-thin" %></p>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-xs-6">
      <!-- %= image_tag 'map-placeholder.png', width: '80%' %> -->
        <div id="map" class="map-show" style="width: 95%; height: 600px;"></div>
      </div>
    </div>

      <div class="row">
            <div class="col-xs-12">
              <p class="text-center location-back">
                <%= link_to :back do  %>
                  <i class="fa fa-arrow-left"></i> Back
                <% end %>
              </p>
            </div>
          </div>

  </div>
</div>
<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).on('ready', function() {
      handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function(){
        markers = handler.addMarkers(<%= raw @markers.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
      });

      $('#categorytype').on('change', function() {
        $('form').submit();
      })
    })
  <% end %>
<% end %>

app/views/locations/new.html.erb
<div class="card">
  <h1 class="text-center">Add a new listing</h1>
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="form">
            <%= simple_form_for @location, html: {multipart: true} do |f| %>
            <%= f.input :name %>
            <%= f.input :description %>
            <%= f.input :telephone %>
            <%= f.input :website %>
            <%= f.input :email %>
            <%= f.label :photo %>
            <%= f.file_field :photo %>
            <%= f.input :street %>
            <%= f.input :city %>
            <%= f.input :postcode %>
            <%= f.input :location_category, collection: [
            'Accommodation',
            'Bar/cafe',
            'Cinema',
            'Cultural site',
            'Museum/Gallery',
            'Park',
            'Private transport',
            'Public transport',
            'Restaurant'] %>
            <!-- %= f.input :validated, wrapper: :vertical_boolean %> -->
              <p><strong>Accessibility</strong></p>
            <%= f.input :wheelchair_access, wrapper: :vertical_boolean %>
            <%= f.input :step_free_access, wrapper: :vertical_boolean %>
            <p><strong>Services</strong></p>
            <%= f.input :automatic_doors, wrapper: :vertical_boolean %>
            <%= f.input :disabled_parking, wrapper: :vertical_boolean %>
            <%= f.input :accessible_toilets, wrapper: :vertical_boolean %>
            <%= f.button :submit, :class => "btn-primary margin-small" %>
            <% end %>
            <i class="fa fa-trash-o"></i><%= link_to 'Cancel', locations_path %>
             <div class="row">
            <div class="col-xs-12">
              <p class="text-center location-back">
                <%= link_to :back do  %>
                  <i class="fa fa-arrow-left"></i> Back
                <% end %>
              </p>
            </div>
          </div>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/locations/show.html.erb
<div class="card">
  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-8">
        <div class="location-infos">
          <h1><%= @location.name.titleize %></h1>
          <div class="row">
            <div class="col-xs-4">
              <% if @location.photo? %>
                <%= image_tag @location.photo.url(:medium), :class=> "pull-left img-responsive" %>
              <% else %>
                <%= image_tag 'placeholder.jpg', width: '40%', :class=> "pull-left img-responsive" %>
              <% end %>
            </div>
            <div class="col-xs-8">
              <div class="location-details">
                <p class="location-category"><%= @location.location_category %></p>
                <p class="description">Description: <%= @location.description %></p>
                <% if @location.telephone? %>
                  <p class="description">Telephone: <%= @location.telephone %></p>
                <% end %>
                <% if @location.website? %>
                  <p class="description">Website: <%= link_to @location.website, @location.website, target: "_blank" %></p>
                <% end %>
                <p class="description">Address: <%= @location.street %>, <%= @location.city %> <%= @location.postcode %></p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-xs-4">

        <!-- %= image_tag 'map-placeholder.png', width: '90%' %> -->
        <div id="map" class="map-show" style="width: 90%; height: 250px"></div>

        <% content_for(:after_js) do %>
          <%= javascript_tag do %>
            $(document).on('ready', function() {
              handler = Gmaps.build('Google');
              handler.buildMap({ internal: { id: 'map' } }, function(){
                markers = handler.addMarkers(<%= raw @markers.to_json %>);
                handler.bounds.extendWith(markers);
                handler.fitMapToBounds();
                handler.getMap().setZoom(14);
              });
            })
          <% end %>
        <% end %>
        <!-- Only if belongs to -->

        <% if current_user && (current_user.id == @location.user_id) %>
          <ul class="text-center list-inline">
            <li><%= link_to 'Edit listing', edit_location_path %></p></li>
          </ul>
        <% end %>
        <!-- % if policy(location).destroy? %> -->
        <!-- % end %> -->
        <!-- % if policy(location).destroy? %> -->

        <!-- <li><%#= link_to "Delete", location_path(@location), :method => :delete , data: { confirm: 'Are you sure?' } %></li> -->
      </div>
    </div>
  </div>
  <div class="container-fluid text-center">
    <div class="location-categories">
      <div class="row">
        <div class="col-xs-12">
          <ul class="list-inline padding-left">
          <% if @location.wheelchair_access? %>
            <li><i class="fa fa-wheelchair"></i>Wheelchair access</li>
          <% end %>
          <% if @location.step_free_access? %>
            <li><%= image_tag "step_free.png", :style=> "height: 18px" %> Step-free access</li>
          <% end %>
          <% if @location.automatic_doors? %>
            <li><%= image_tag "doors.png", :style=> "height: 25px" %> Automatic doors</li>
          <% end %>
          <% if @location.disabled_parking? %>
            <li><%= image_tag "parking.png", :style=> "height: 18px" %> Disabled parking</li>
          <% end %>
          <% if @location.accessible_toilets? %>
            <li><%= image_tag "toilets.png", :style=> "height: 18px" %></i> Accessible toilets</li>
          <% end %>
          </ul>
        </div>
          </div>
        </div>
        <% if @location.reviews.present? %>
          <% @location.reviews.each do |review| %>
            <div class="review-box">
              <div class="row clear">
                <div class="col-xs-2 text-right">
                  <%= image_tag(review.user.picture.url(:medium), :class=> "img-show-avatar") %>
                </div>
                <div class="col-xs-10">
                  <div class="speech-bubble">
                    <div class="arrow left"></div>
                    <div class="review-info">
                      by <%= review.user.name %>
                      at <%= "#{review.created_at.strftime('%v %R')}" %>
                    </div>
                    <div class="rating">
                      <% review.rating.times do %>
                        <i class="fa fa-star on padding-sides-3"></i>
                      <% end %>
                      <% (5 - review.rating).times do %>
                        <i class="fa fa-star grey padding-sides-3"></i>
                      <% end %>
                        <br><%= review.content %>
                    </div>
                  </div>
                </div>
            </div>
          <% end %>

        <% else %>

          <div class="row">
            <div class="col-xs-12 padding-left">
              <p class="review-box">Be the first to <%= link_to 'leave a review', new_location_review_path(@location), class: "btn btn-warning btn-sm" %></p>
               <% end %>
            </div>
          </div>


          <div class="row">
            <div class="col-xs-12">
              <p class="text-center location-back">
                <%= link_to :back do  %>
                  <i class="fa fa-arrow-left"></i> Back
                <% end %>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>